### ISSUE TITLE
Document issue with leaky subtree command and running out of inodes

### ISSUE THREAD

**Issue by simensen** [dflydev/git-subsplit#15]
This is a known issue and has been reported in #14. Until the underlying subtree command is patched we should warn people about the problem and suggest cleaning up the cache directory by hand, either after each build or regularly by way of a cron job.

**Comment by mnapoli** [comment]
This issue can be closed as the README mentions that problem :)

**Comment by simensen** [comment]
@mnapoli thanks. :)
